config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard/check_referral_code'
  resources :dashboard
  resources :user_profiles
  resources :customers
  root 'dashboard#index'

  devise_for :users, controllers: {registrations: 'users/registrations'}

end

app/models/business_category.rb
class BusinessCategory < ActiveRecord::Base
	belongs_to :user_profile
end

app/models/customer.rb
class Customer < ActiveRecord::Base

	has_one :source
	belongs_to :user
end

app/models/referral_code.rb
class ReferralCode < ActiveRecord::Base
end

app/models/source.rb
class Source < ActiveRecord::Base
	belongs_to :customer
end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :user_profile
  has_many :customers
  accepts_nested_attributes_for :user_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
	
	has_one :business_category
	belongs_to :user
	validates_presence_of :first_name, :last_name, :business_name, :business_category_id, :phone_number, :office_number, :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
layout "dashboard"

def index
	@customers = Customer.all
end

def new
  @customer = Customer.new
end

def create
	@customer = Customer.new(customer_params)
	@customer.user_id = current_user.id
	respond_to do |format|
	if @customer.save
		format.html {redirect_to :back, notice: "Customer Added"}
		format.js
	else
		format.html { redirect_to :back, notice: "Saving Failed"}
		format.js
	end
end
end
private

def customer_params
params[:customer].permit(:name, :email, :source_id)
end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_user!
	layout "dashboard"
	def index
	end

	def check_referral_code
	if ReferralCode.exists?(:referral_code => params[:coupon])
      valid = true
      @coupon = Coupon.find_by(:code => params[:coupon])
      puts "Code Valid"
    else
      valid = false
      puts "Code Invalid"
    end
    respond_to do |format|
      if valid
        format.json { render :json => @coupon }
      else
        format.json { }
      end
      return
    end

	end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]
before_filter :configure_permitted_parameters

def new
    # Override Devise default behaviour and create a profile as well
    build_resource({})
    resource.build_user_profile
    respond_with self.resource
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end



 
 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u|
      u.permit(:email, :password, :password_confirmation, :user_profile_attributes => [:first_name, :last_name, :business_name, :business_category_id, :website, :address, :phone_number, :office_number])
    }
  end
 
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/customers/create.js.erb
$(".form-control").val('')

app/views/customers/index.html.erb
                    <!-- First Row -->
                    <div class="row">
                        <!-- Simple Stats Widgets -->
                        <div class="col-sm-6 col-lg-3">
                            <a href="javascript:void(0)" class="widget">
                                <div class="widget-content widget-content-mini text-right clearfix">
                                    <div class="widget-icon pull-left themed-background">
                                        <i class="gi gi-cardio text-light-op"></i>
                                    </div>
                                    <h2 class="widget-heading h3">
                                        <strong><span data-toggle="counter" data-to="2835"></span></strong>
                                    </h2>
                                    <span class="text-muted">Today</span>
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <a href="javascript:void(0)" class="widget">
                                <div class="widget-content widget-content-mini text-right clearfix">
                                    <div class="widget-icon pull-left themed-background-success">
                                        <i class="gi gi-user text-light-op"></i>
                                    </div>
                                    <h2 class="widget-heading h3 text-success">
                                        <strong>+ <span data-toggle="counter" data-to="2862"></span></strong>
                                    </h2>
                                    <span class="text-muted">THIS WEEK</span>
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <a href="javascript:void(0)" class="widget">
                                <div class="widget-content widget-content-mini text-right clearfix">
                                    <div class="widget-icon pull-left themed-background-warning">
                                        <i class="gi gi-briefcase text-light-op"></i>
                                    </div>
                                    <h2 class="widget-heading h3 text-warning">
                                        <strong>+ <span data-toggle="counter" data-to="75"></span></strong>
                                    </h2>
                                    <span class="text-muted">TOTAL</span>
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <a href="javascript:void(0)" class="widget">
                                <div class="widget-content widget-content-mini text-right clearfix">
                                    <div class="widget-icon pull-left themed-background-danger">
                                        <i class="gi gi-wallet text-light-op"></i>
                                    </div>
                                    <h2 class="widget-heading h3 text-danger">
                                        <strong>$ <span data-toggle="counter" data-to="5820"></span></strong>
                                    </h2>
                                    <span class="text-muted">UNSUBSCRIBED</span>
                                </div>
                            </a>
                        </div>
                        <!-- END Simple Stats Widgets -->
                    </div>
                    <!-- END First Row --> 
                    <!-- Datatables Block -->
                    <!-- Datatables is initialized in js/pages/uiTables.js -->
                    <div class="block full">
                        <div class="block-title">
                            <h2>Datatables</h2>
                        </div>
                        <div class="table-responsive">
                            <table id="example-datatable" class="table table-striped table-bordered table-vcenter">
                                <thead>
                                    <tr>
                                        <th class="text-center" style="width: 50px;">ID</th>
                                        <th>User</th>
                                        <th>Email</th>
                                        <th style="width: 120px;">Profile Status</th>
                                        <th class="text-center" style="width: 75px;"><i class="fa fa-flash"></i></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% current_user.customers.each do |customer| %>
                                    <tr>
                                        <td class="text-center">1</td>
                                        <td><strong><%= customer.name %></strong></td>
                                        <td><%= customer.email %></td>
                                        <td><span class="label label-warning">not filled</span></td>
                                        <td class="text-center">
                                            <a href="javascript:void(0)" data-toggle="tooltip" title="Edit User" class="btn btn-effect-ripple btn-xs btn-success"><i class="fa fa-pencil"></i></a>
                                            <a href="javascript:void(0)" data-toggle="tooltip" title="Delete User" class="btn btn-effect-ripple btn-xs btn-danger"><i class="fa fa-times"></i></a>
                                        </td>
                                    </tr>
                                    <% end %>
                                </tbody>
                            </table>
                        </div>
                    </div>
                        <!-- END Datatables Block -->

app/views/dashboard/index.html.erb
                    <!-- First Row -->
                    <div class="row">
                        <!-- Simple Stats Widgets -->
                        <div class="col-sm-6 col-lg-3">
                            <a href="javascript:void(0)" class="widget">
                                <div class="widget-content widget-content-mini text-right clearfix">
                                    <div class="widget-icon pull-left themed-background">
                                        <i class="gi gi-cardio text-light-op"></i>
                                    </div>
                                    <h2 class="widget-heading h3">
                                        <strong><span data-toggle="counter" data-to="2835"></span></strong>
                                    </h2>
                                    <span class="text-muted">SALES</span>
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <a href="javascript:void(0)" class="widget">
                                <div class="widget-content widget-content-mini text-right clearfix">
                                    <div class="widget-icon pull-left themed-background-success">
                                        <i class="gi gi-user text-light-op"></i>
                                    </div>
                                    <h2 class="widget-heading h3 text-success">
                                        <strong>+ <span data-toggle="counter" data-to="2862"></span></strong>
                                    </h2>
                                    <span class="text-muted">NEW USERS</span>
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <a href="javascript:void(0)" class="widget">
                                <div class="widget-content widget-content-mini text-right clearfix">
                                    <div class="widget-icon pull-left themed-background-warning">
                                        <i class="gi gi-briefcase text-light-op"></i>
                                    </div>
                                    <h2 class="widget-heading h3 text-warning">
                                        <strong>+ <span data-toggle="counter" data-to="75"></span></strong>
                                    </h2>
                                    <span class="text-muted">PROJECTS</span>
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-6 col-lg-3">
                            <a href="javascript:void(0)" class="widget">
                                <div class="widget-content widget-content-mini text-right clearfix">
                                    <div class="widget-icon pull-left themed-background-danger">
                                        <i class="gi gi-wallet text-light-op"></i>
                                    </div>
                                    <h2 class="widget-heading h3 text-danger">
                                        <strong>$ <span data-toggle="counter" data-to="5820"></span></strong>
                                    </h2>
                                    <span class="text-muted">EARNINGS</span>
                                </div>
                            </a>
                        </div>
                        <!-- END Simple Stats Widgets -->
                    </div>
                    <!-- END First Row -->    


                    <!-- Tables Row -->
                    <div class="row">
                        <div class="col-lg-6">
                            <!-- Partial Responsive Block -->
                            <div class="block">
                                <!-- Partial Responsive Title -->
                                <div class="block-title">
                                    <h2>Recent Customers</h2>
                                </div>
                                <!-- END Partial Responsive Title -->

                                <!-- Partial Responsive Content -->
                                <table class="table table-striped table-borderless table-vcenter">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th class="hidden-xs">Email</th>
                                            <th class="hidden-sm hidden-xs">Profile Status</th>
                                            <th style="width: 80px;" class="text-center"><i class="fa fa-flash"></i></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% current_user.customers.take(10).each do |customer| %>
                                        <tr>
                                            <td><strong><%= customer.name.titleize %></strong></td>
                                            <td class="hidden-xs"><%= customer.email %></td>
                                            <td class="hidden-sm hidden-xs"><a href="javascript:void(0)" class="label label-warning">Not Filled</a></td>
                                            <td class="text-center">
                                                <a href="javascript:void(0)" data-toggle="tooltip" title="Edit User" class="btn btn-effect-ripple btn-xs btn-success"><i class="fa fa-pencil"></i></a>
                                                <a href="javascript:void(0)" data-toggle="tooltip" title="Delete User" class="btn btn-effect-ripple btn-xs btn-danger"><i class="fa fa-times"></i></a>
                                            </td>
                                        </tr>
                                        <% end %>
                                    </tbody>
                                </table>
                                <!-- END Partial Responsive Content -->
                            </div>
                            <!-- END Partial Responsive Block -->
                        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Salespro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/partials/_sidebar.html.erb
                <!-- Main Sidebar -->
                <div id="sidebar">
                    <!-- Sidebar Brand -->
                    <div id="sidebar-brand" class="themed-background">
                        <%= link_to "dashboard", class: "sidebar-title" do %>
                            <i class="fa fa-shopping-cart"></i> <span class="sidebar-nav-mini-hide">SALES<strong>PRO</strong></span>
                        <% end %>
                    </div>
                    <!-- END Sidebar Brand -->

                    <!-- Wrapper for scrolling functionality -->
                    <div id="sidebar-scroll">
                        <!-- Sidebar Content -->
                        <div class="sidebar-content">
                            <!-- Sidebar Navigation -->
                            <ul class="sidebar-nav">
                                <li>
                                    <%= link_to "dashboard", class: "active" do %>
                                    <i class="gi gi-compass sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Dashboard</span>
                                    <% end %>
                                </li>
                                <li class="sidebar-separator">
                                    <i class="fa fa-ellipsis-h"></i>
                                </li>
                                <li>
                                    <%= link_to customers_path do %>
                                    <i class="gi gi-user sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Customers</span>
                                    <% end %>
                                </li>
                                <li>
                                    <a href="#" class="sidebar-nav-menu"><i class="fa fa-chevron-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="hi hi-send sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Templates</span></a>
                                    <ul>
                                        <li>
                                            <a href="javascript:void(0)">Add New Template</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)">My Templates</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#" class="sidebar-nav-menu"><i class="fa fa-chevron-left sidebar-nav-indicator sidebar-nav-mini-hide"></i><i class="gi gi-message_full sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Campaigns</span></a>
                                    <ul>
                                        <li>
                                            <a href="javascript:void(0)">Start a Campaign</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)">Running Campaigns</a>
                                        </li>
                                                                                <li>
                                            <a href="javascript:void(0)">Completed Campaigns</a>
                                        </li>
                                                                                <li>
                                            <a href="javascript:void(0)">All Campaigns</a>
                                        </li>
                                                                                <li>
                                            <a href="javascript:void(0)">Campaign Reports</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <!-- END Sidebar Navigation -->
                        </div>
                        <!-- END Sidebar Content -->
                    </div>
                    <!-- END Wrapper for scrolling functionality -->

                    <!-- Sidebar Extra Info -->
                    <div id="sidebar-extra-info" class="sidebar-content sidebar-nav-mini-hide">
                      
                        
                        <div class="text-center">
                            <small>Built with <i class="fa fa-heart text-danger"></i> using <a href="#" target="_blank">rails</a></small><br>
                            <small><span id="year-copy"></span> &copy; <a href="#" target="_blank">SalesPro</a></small>
                        </div>
                    </div>
                    <!-- END Sidebar Extra Info -->
                </div>
                <!-- END Main Sidebar -->